FROM apache/airflow:2.8.1-python3.11

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    yfinance \
    pandas \
    tenacity \
    loguru \
    psycopg2-binary \
    pydantic

ENV PYTHONPATH="${PYTHONPATH}:/opt/airflow/repo"