FROM apache/airflow:2.8.1-python3.11

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    openjdk-17-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"

USER airflow

RUN pip install --no-cache-dir \
    yfinance \
    pandas \
    tenacity \
    loguru \
    psycopg2-binary \
    pydantic \
    pyspark

ENV PYTHONPATH="${PYTHONPATH}:/opt/airflow/repo"